# Generated by Django 2.2.5 on 2019-09-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bringer',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
